#!/usr/bin/env python3
"""Test migration: append grants for one user from ad_authorized_grants CSV."""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path
from urllib.parse import urlsplit

from atrust_common import (
    ATrustClient,
    DEFAULT_CONFIG_FILE,
    apply_config,
    grant_from_csv_row,
    read_csv,
    require_config_values,
    write_csv,
)


OUTPUT_FIELDS = [
    "status",
    "ad_user_id",
    "ad_user_name",
    "ad_description",
    "feishu_user_id",
    "feishu_user_name",
    "feishu_description",
    "feishu_user_id_value",
    "feishu_external_id",
    "match_target_field",
    "grant_kind",
    "resource_id",
    "resource_name",
    "grant_source_type",
    "grant_source_id",
    "grant_source_name",
    "effective_time",
    "expire_time",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Migrate one user's grants from ad_authorized_grants CSV.")
    parser.add_argument("--ad-description", required=True, help="AD description value to migrate, for example HCXXXXXXXX.")
    parser.add_argument(
        "--input-csv",
        default="outputs/precheck/ad_authorized_grants_10.csv",
        help="CSV generated by 01_prepare_ad_authorized_grants.py.",
    )
    parser.add_argument("--config", default=DEFAULT_CONFIG_FILE, help="JSON config file path.")
    parser.add_argument("--base-url", help="aTrust base URL, for example https://1.1.1.1:4433")
    parser.add_argument("--api-id", help="OpenAPI API ID")
    parser.add_argument("--api-secret", help="OpenAPI API secret")
    parser.add_argument("--ad-domain", help="AD user directory domain")
    parser.add_argument("--feishu-domain", help="Feishu user directory domain")
    parser.add_argument("--execute", action="store_true", help="Actually append grants. Without this flag, dry-run only.")
    parser.add_argument("--insecure", action="store_true", help="Disable TLS certificate verification.")
    parser.add_argument("--timeout", type=int, default=30, help="HTTP timeout in seconds.")
    parser.add_argument("--max-ops-per-second", type=float, default=None, help="Default: 8.")
    parser.add_argument("--output-dir", default="outputs/test", help="Directory for this script's outputs.")
    return parser.parse_args()


def validate_base_url(base_url: str) -> bool:
    base_path = urlsplit(base_url).path
    if base_path and base_path != "/":
        print("--base-url should only include scheme/host/port, not an API path.", file=sys.stderr)
        return False
    return True


def matching_rows(rows: list[dict[str, str]], ad_description: str) -> list[dict[str, str]]:
    target = ad_description.strip().lower()
    return [row for row in rows if str(row.get("ad_description") or "").strip().lower() == target]


def result_rows(status: str, rows: list[dict[str, str]]) -> list[dict[str, str]]:
    output: list[dict[str, str]] = []
    for row in rows:
        output.append(
            {
                "status": status,
                "ad_user_id": row.get("ad_user_id", ""),
                "ad_user_name": row.get("ad_user_name", ""),
                "ad_description": row.get("ad_description", ""),
                "feishu_user_id": row.get("feishu_user_id", ""),
                "feishu_user_name": row.get("feishu_user_name", ""),
                "feishu_description": row.get("feishu_description", ""),
                "feishu_user_id_value": row.get("feishu_user_id_value", ""),
                "feishu_external_id": row.get("feishu_external_id", ""),
                "match_target_field": row.get("match_target_field", ""),
                "grant_kind": row.get("grant_kind", ""),
                "resource_id": row.get("resource_id", ""),
                "resource_name": row.get("resource_name", ""),
                "grant_source_type": row.get("grant_source_type", ""),
                "grant_source_id": row.get("grant_source_id", ""),
                "grant_source_name": row.get("grant_source_name", ""),
                "effective_time": row.get("effective_time", ""),
                "expire_time": row.get("expire_time", ""),
            }
        )
    return output


def main() -> int:
    args = apply_config(parse_args())
    if not require_config_values(args) or not validate_base_url(args.base_url):
        return 2

    rows = read_csv(args.input_csv)
    selected_rows = matching_rows(rows, args.ad_description)
    if not selected_rows:
        print(f"No rows found in {args.input_csv} for ad_description={args.ad_description}", file=sys.stderr)
        return 1

    feishu_user_ids = {str(row.get("feishu_user_id") or "").strip() for row in selected_rows}
    feishu_user_ids.discard("")
    if len(feishu_user_ids) != 1:
        print(f"Expected exactly one Feishu user ID, found: {sorted(feishu_user_ids)}", file=sys.stderr)
        return 1

    feishu_user_id = next(iter(feishu_user_ids))
    grants = [grant_from_csv_row(row) for row in selected_rows]
    output_dir = Path(args.output_dir)
    status = "assigned" if args.execute else "dry_run"
    write_csv(output_dir / "test_user_grants.csv", result_rows(status, selected_rows), OUTPUT_FIELDS)

    failed_rows: list[dict[str, str]] = []
    if args.execute:
        client = ATrustClient(
            args.base_url,
            args.api_id,
            args.api_secret,
            timeout=args.timeout,
            verify_tls=not args.insecure,
            max_ops_per_second=args.max_ops_per_second,
        )
        try:
            client.assign_to_user_by_id(args.feishu_domain, feishu_user_id, grants)
        except Exception as exc:  # noqa: BLE001 - write a useful failure row and return non-zero.
            first = selected_rows[0]
            failed_rows.append(
                {
                    "ad_user_id": first.get("ad_user_id", ""),
                    "ad_user_name": first.get("ad_user_name", ""),
                    "ad_description": first.get("ad_description", ""),
                    "feishu_user_id": first.get("feishu_user_id", ""),
                    "feishu_user_name": first.get("feishu_user_name", ""),
                    "error": str(exc),
                }
            )

    write_csv(
        output_dir / "test_failed.csv",
        failed_rows,
        ["ad_user_id", "ad_user_name", "ad_description", "feishu_user_id", "feishu_user_name", "error"],
    )
    grouped = defaultdict(int)
    for row in selected_rows:
        grouped[row.get("grant_kind", "")] += 1
    print(f"Selected user: {selected_rows[0].get('ad_description')} -> Feishu ID {feishu_user_id}")
    print(f"Grant rows {'assigned' if args.execute else 'planned'}: {len(selected_rows)}")
    print(f"Grant kind counts: {dict(grouped)}")
    print(f"Outputs written to: {output_dir.resolve()}")
    if not args.execute:
        print("Dry-run only. Re-run with --execute to append this user's grants.")
    return 0 if not failed_rows else 1


if __name__ == "__main__":
    raise SystemExit(main())
