#!/usr/bin/env python3
"""Formal migration: append all grants from ad_authorized_grants.csv."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from urllib.parse import urlsplit

from atrust_common import (
    ATrustClient,
    DEFAULT_CONFIG_FILE,
    apply_config,
    group_csv_grants_by_feishu_user,
    read_csv,
    require_config_values,
    write_csv,
)


OUTPUT_FIELDS = [
    "status",
    "ad_user_id",
    "ad_user_name",
    "ad_description",
    "feishu_user_id",
    "feishu_user_name",
    "feishu_description",
    "feishu_user_id_value",
    "feishu_external_id",
    "match_target_field",
    "grant_kind",
    "resource_id",
    "resource_name",
    "grant_source_type",
    "grant_source_id",
    "grant_source_name",
    "effective_time",
    "expire_time",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Migrate all grants from ad_authorized_grants.csv.")
    parser.add_argument(
        "--input-csv",
        default="outputs/precheck/ad_authorized_grants.csv",
        help="Full CSV generated by 01_prepare_ad_authorized_grants.py --full.",
    )
    parser.add_argument("--config", default=DEFAULT_CONFIG_FILE, help="JSON config file path.")
    parser.add_argument("--base-url", help="aTrust base URL, for example https://1.1.1.1:4433")
    parser.add_argument("--api-id", help="OpenAPI API ID")
    parser.add_argument("--api-secret", help="OpenAPI API secret")
    parser.add_argument("--ad-domain", help="AD user directory domain")
    parser.add_argument("--feishu-domain", help="Feishu user directory domain")
    parser.add_argument("--execute", action="store_true", help="Actually append grants. Without this flag, dry-run only.")
    parser.add_argument("--insecure", action="store_true", help="Disable TLS certificate verification.")
    parser.add_argument("--timeout", type=int, default=30, help="HTTP timeout in seconds.")
    parser.add_argument("--max-ops-per-second", type=float, default=None, help="Default: 8.")
    parser.add_argument("--output-dir", default="outputs/formal", help="Directory for this script's outputs.")
    return parser.parse_args()


def validate_base_url(base_url: str) -> bool:
    base_path = urlsplit(base_url).path
    if base_path and base_path != "/":
        print("--base-url should only include scheme/host/port, not an API path.", file=sys.stderr)
        return False
    return True


def output_row(status: str, row: dict[str, str]) -> dict[str, str]:
    return {
        "status": status,
        "ad_user_id": row.get("ad_user_id", ""),
        "ad_user_name": row.get("ad_user_name", ""),
        "ad_description": row.get("ad_description", ""),
        "feishu_user_id": row.get("feishu_user_id", ""),
        "feishu_user_name": row.get("feishu_user_name", ""),
        "feishu_description": row.get("feishu_description", ""),
        "feishu_user_id_value": row.get("feishu_user_id_value", ""),
        "feishu_external_id": row.get("feishu_external_id", ""),
        "match_target_field": row.get("match_target_field", ""),
        "grant_kind": row.get("grant_kind", ""),
        "resource_id": row.get("resource_id", ""),
        "resource_name": row.get("resource_name", ""),
        "grant_source_type": row.get("grant_source_type", ""),
        "grant_source_id": row.get("grant_source_id", ""),
        "grant_source_name": row.get("grant_source_name", ""),
        "effective_time": row.get("effective_time", ""),
        "expire_time": row.get("expire_time", ""),
    }


def first_rows_by_feishu_user(rows: list[dict[str, str]]) -> dict[str, dict[str, str]]:
    first_rows: dict[str, dict[str, str]] = {}
    for row in rows:
        feishu_user_id = str(row.get("feishu_user_id") or "").strip()
        if feishu_user_id:
            first_rows.setdefault(feishu_user_id, row)
    return first_rows


def rows_by_feishu_user(rows: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        feishu_user_id = str(row.get("feishu_user_id") or "").strip()
        if feishu_user_id:
            grouped[feishu_user_id].append(row)
    return grouped


def main() -> int:
    args = apply_config(parse_args())
    if not require_config_values(args) or not validate_base_url(args.base_url):
        return 2

    rows = read_csv(args.input_csv)
    grants_by_user = group_csv_grants_by_feishu_user(rows)
    rows_grouped = rows_by_feishu_user(rows)
    first_rows = first_rows_by_feishu_user(rows)

    output_dir = Path(args.output_dir)
    status = "assigned" if args.execute else "dry_run"
    planned_rows = [output_row(status, row) for row in rows]
    write_csv(output_dir / "all_grants_result.csv", planned_rows, OUTPUT_FIELDS)

    failed_rows: list[dict[str, str]] = []
    if args.execute:
        client = ATrustClient(
            args.base_url,
            args.api_id,
            args.api_secret,
            timeout=args.timeout,
            verify_tls=not args.insecure,
            max_ops_per_second=args.max_ops_per_second,
        )
        for feishu_user_id, grants in grants_by_user.items():
            first = first_rows.get(feishu_user_id, {})
            try:
                client.assign_to_user_by_id(args.feishu_domain, feishu_user_id, grants)
            except Exception as exc:  # noqa: BLE001 - keep migrating the remaining users.
                failed_rows.append(
                    {
                        "ad_user_id": first.get("ad_user_id", ""),
                        "ad_user_name": first.get("ad_user_name", ""),
                        "ad_description": first.get("ad_description", ""),
                        "feishu_user_id": first.get("feishu_user_id", feishu_user_id),
                        "feishu_user_name": first.get("feishu_user_name", ""),
                        "grant_rows": str(len(rows_grouped.get(feishu_user_id, []))),
                        "error": str(exc),
                    }
                )

    write_csv(
        output_dir / "all_failed.csv",
        failed_rows,
        ["ad_user_id", "ad_user_name", "ad_description", "feishu_user_id", "feishu_user_name", "grant_rows", "error"],
    )
    summary = {
        "mode": "execute" if args.execute else "dry_run",
        "input_csv": str(Path(args.input_csv).resolve()),
        "feishu_user_count": len(grants_by_user),
        "grant_row_count": len(rows),
        "failed_user_count": len(failed_rows),
        "grant_kind_counts": dict(Counter(row.get("grant_kind", "") for row in rows)),
    }
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"Feishu users to migrate: {len(grants_by_user)}")
    print(f"Grant rows {'assigned' if args.execute else 'planned'}: {len(rows)}")
    print(f"Failed user assignments: {len(failed_rows)}")
    print(f"Outputs written to: {output_dir.resolve()}")
    if not args.execute:
        print("Dry-run only. Re-run with --execute to append all grants from the CSV.")
    return 0 if not failed_rows else 1


if __name__ == "__main__":
    raise SystemExit(main())
