#!/usr/bin/env python3
"""Production: migrate all users' grants from ad_authorized_grants.csv to Feishu."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from urllib.parse import urlsplit

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ad_description_to_feishu_description_common import (  # noqa: E402
    ASSIGNMENT_REPORT_COLUMNS,
    FAILED_REPORT_COLUMNS,
    add_common_args,
    apply_config,
    build_assignment_rows,
    missing_required_options,
    read_grant_detail_csv,
)
from atrust_feishu_resource_sync import ATrustClient, write_csv  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Migrate all users' grants from precheck CSV to Feishu.")
    add_common_args(parser, default_output_dir="output-production-from-csv")
    parser.add_argument(
        "--grant-csv",
        default="output-precheck-ad-description-to-feishu-description/ad_authorized_grants.csv",
        help="CSV generated by the precheck script.",
    )
    parser.add_argument("--execute", action="store_true", help="Actually append grants. Without it, dry-run reports only.")
    return parser.parse_args()


def main() -> int:
    args = apply_config(parse_args())
    missing = missing_required_options(args)
    if missing:
        for option in missing:
            print(f"{option} is required unless set in --config.", file=sys.stderr)
        return 2
    if not Path(args.grant_csv).exists():
        print(f"Grant CSV not found: {args.grant_csv}", file=sys.stderr)
        return 2
    base_path = urlsplit(args.base_url).path
    if base_path and base_path != "/":
        print("--base-url should only include scheme/host/port, not an API path.", file=sys.stderr)
        return 2

    users_by_feishu_id = read_grant_detail_csv(args.grant_csv)
    output_dir = Path(args.output_dir)
    assigned_rows: list[dict] = []
    failed_rows: list[dict] = []
    client = None
    if args.execute:
        client = ATrustClient(
            args.base_url,
            args.api_id,
            args.api_secret,
            timeout=args.timeout,
            verify_tls=not args.insecure,
            max_ops_per_second=args.max_ops_per_second,
        )
    else:
        print("Dry-run only. Re-run with --execute to append grants for all users in the CSV.")

    for user in users_by_feishu_id.values():
        grants = user["grants"]
        status = "dry_run"
        if args.execute and client is not None:
            try:
                client.assign_to_user_by_id(args.feishu_domain, user["feishu_user_id"], grants)
                status = "assigned"
            except Exception as exc:  # noqa: BLE001 - report and continue with other users.
                failed_rows.append(
                    {
                        "ad_user_id": user["ad_user_id"],
                        "ad_user_name": user["ad_user_name"],
                        "ad_description": user["ad_description"],
                        "feishu_user_id": user["feishu_user_id"],
                        "feishu_user_name": user["feishu_user_name"],
                        "feishu_description": user["feishu_description"],
                        "error": str(exc),
                    }
                )
                continue
        assigned_rows.extend(build_assignment_rows(status, user, grants))

    write_csv(output_dir / "all_assigned_grants.csv", assigned_rows, ASSIGNMENT_REPORT_COLUMNS)
    write_csv(output_dir / "all_failed.csv", failed_rows, FAILED_REPORT_COLUMNS)
    print(f"Users in CSV: {len(users_by_feishu_id)}")
    print(f"Grant rows {'assigned' if args.execute else 'planned'}: {len(assigned_rows)}")
    print(f"Failed user assignments: {len(failed_rows)}")
    print(f"Reports written to: {output_dir.resolve()}")
    return 0 if not failed_rows else 1


if __name__ == "__main__":
    raise SystemExit(main())
