#!/usr/bin/env python3
"""Test: migrate one user's grants from ad_authorized_grants.csv to Feishu."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from urllib.parse import urlsplit

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ad_description_to_feishu_description_common import (  # noqa: E402
    ASSIGNMENT_REPORT_COLUMNS,
    FAILED_REPORT_COLUMNS,
    add_common_args,
    apply_config,
    build_assignment_rows,
    missing_required_options,
    read_grant_detail_csv,
    select_one_user,
)
from atrust_feishu_resource_sync import ATrustClient, write_csv  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Migrate one user's grants from precheck CSV to Feishu.")
    add_common_args(parser, default_output_dir="output-test-one-user-from-csv")
    parser.add_argument(
        "--grant-csv",
        default="output-precheck-ad-description-to-feishu-description/ad_authorized_grants.csv",
        help="CSV generated by the precheck script.",
    )
    parser.add_argument("--ad-description", help="AD description value to migrate. Default: first user in CSV.")
    parser.add_argument("--execute", action="store_true", help="Actually append grants. Without it, dry-run reports only.")
    return parser.parse_args()


def main() -> int:
    args = apply_config(parse_args())
    missing = missing_required_options(args)
    if missing:
        for option in missing:
            print(f"{option} is required unless set in --config.", file=sys.stderr)
        return 2
    if not Path(args.grant_csv).exists():
        print(f"Grant CSV not found: {args.grant_csv}", file=sys.stderr)
        return 2
    base_path = urlsplit(args.base_url).path
    if base_path and base_path != "/":
        print("--base-url should only include scheme/host/port, not an API path.", file=sys.stderr)
        return 2

    users_by_feishu_id = read_grant_detail_csv(args.grant_csv)
    user = select_one_user(users_by_feishu_id, args.ad_description)
    if not user:
        print("Could not select exactly one user from CSV. Pass --ad-description with a unique value.", file=sys.stderr)
        return 1
    grants = user["grants"]
    output_dir = Path(args.output_dir)
    failed_rows: list[dict] = []
    status = "dry_run"

    if args.execute:
        client = ATrustClient(
            args.base_url,
            args.api_id,
            args.api_secret,
            timeout=args.timeout,
            verify_tls=not args.insecure,
            max_ops_per_second=args.max_ops_per_second,
        )
        try:
            client.assign_to_user_by_id(args.feishu_domain, user["feishu_user_id"], grants)
            status = "assigned"
        except Exception as exc:  # noqa: BLE001 - write a clear CSV report.
            failed_rows.append(
                {
                    "ad_user_id": user["ad_user_id"],
                    "ad_user_name": user["ad_user_name"],
                    "ad_description": user["ad_description"],
                    "feishu_user_id": user["feishu_user_id"],
                    "feishu_user_name": user["feishu_user_name"],
                    "feishu_description": user["feishu_description"],
                    "error": str(exc),
                }
            )
    else:
        print("Dry-run only. Re-run with --execute to append grants for this user.")

    write_csv(output_dir / "one_user_assigned_grants.csv", build_assignment_rows(status, user, grants), ASSIGNMENT_REPORT_COLUMNS)
    write_csv(output_dir / "one_user_failed.csv", failed_rows, FAILED_REPORT_COLUMNS)
    print(f"Selected AD description: {user['ad_description']}")
    print(f"Feishu user id: {user['feishu_user_id']}")
    print(f"Grant rows: {len(grants)}")
    print(f"Failed user assignments: {len(failed_rows)}")
    print(f"Reports written to: {output_dir.resolve()}")
    return 0 if not failed_rows else 1


if __name__ == "__main__":
    raise SystemExit(main())
